#!/usr/bin/env bash
set -euo pipefail

case "${1:-}" in
  nightly|preview|stable)
    ;;
  *)
    echo "Error: Invalid argument '${1:-}'"
    echo "Usage: $0 {nightly|preview|stable}"
    exit 1
    ;;
esac

which gh >/dev/null || brew install gh

if [ "$1" == "nightly" ]; then
  git fetch origin main:tags/nightly -f
  git log --oneline -1 nightly
  git push -f origin nightly
  exit
fi

version=$(./script/get-released-version "$1" | sed 's/\.[^\.]*$/.x/')
echo "Bumping $1 (v$version)"

gh workflow run "bump_patch_version.yml" -f branch="v$version"
echo "Follow along at: https://github.com/zed-industries/zed/actions"
